// Design System Workspace Design Tokens — JS module
// Auto-generated by scripts/generate-tokens.js — do not edit
//
// Usage:
//   const { colorSemantic } = require('./tokens');
//   colorSemantic['background/page']  // → "#FFFFFF"

/* eslint-disable */

const colorPrimitive = {
  "neutral/0": "#FFFFFF",
  "neutral/900": "#111111",
  "accent/500": "#2F6FED"
};

const colorSemantic = {
  "background/page": "#FFFFFF",
  "text/default": "#111111",
  "action/primary": "#2F6FED"
};

const space = {
  "space/s": 8,
  "space/m": 16,
  "space/l": 24,
  "radius/s": 4
};

const motion = {
  "duration/fast": 160,
  "duration/base": 240,
  "easing/standard": "cubic-bezier(0.2, 0, 0, 1)"
};

const type = {
  "type/body": {
    "fontFamily": "Inter",
    "fontWeight": 400,
    "fontSize": 16,
    "lineHeight": {
      "unit": "PERCENT",
      "value": 150
    },
    "letterSpacing": {
      "unit": "PIXELS",
      "value": 0
    }
  }
};

const shadow = {};

const grid = {};

module.exports = {
  colorPrimitive,
  colorSemantic,
  space,
  motion,
  type,
  shadow,
  grid,
};
